### ISSUE TITLE
Show error from rebalancer or failover or any background service

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#107]

**Comment by Gerold103** [comment]
In `storage.info()` and `router.info()`

**Comment by Khatskevich** [comment]
How an error report mechanism may work:

One calls `storage.info()` and sees a report like this:
```
...
bg_fibers:
    failover:
         status: "error",
         description: "error message"
...
```
Problems:
1. The error should be deleted when it disappears
2. The error should not be deleted when it still exists

Solution:
1. Introduce a function set_fiber_state, which
   a. extracts `fiber.name()`
   b. takes error id, which consists of:
         * uniquie error id
         * bucket_id in case it is related to a bucket
    c. changes status ok -> error in any case
    d. changes error -> error in any case
    e. changes error -> ok only if id of the change and of the current error are the same
2. flush errors on all bucket send, configure, reconfigure... to garantee `1.e` successfull error disabling

**Comment by Khatskevich** [comment]
# Solution 2
Discussed verbally with @Gerold103 : this solution is more preferable due to its simplicity.
Here is a high-level overview:

Methods:
1. log event
2. log status

Result of `storage.info()` call:
```
...
fibers:
   rebalancer:
      status: sleeping
      last_messages:
               31m: repicaset 1 is up
               36m: replicaset 1 is unreachable
               .....
...
```

## Log event
Overload (wrap) `log` module, to implement the interface like this:
`new_log.error("message", varargs)`.
This function also uses:
1. current time
2. fiber name

And stores last errors into some data structure

## Log status
Shows current activity of the fiber:
1. sleeping
2. receiving buckets
3. ...
