### ISSUE TITLE
Do not move bucket with running stored procedure

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/vshard#122]
In case stored procedure yields and RPS is high, the following situation is very likely to happen:

1. One calls stored procedure
2. It yields
3. bucket started moving to another replicates
4. inconsistent state

**Comment by Gerold103** [comment]
It is impossible when a function uses transactions. If an operation on a bucket is atomic, then it can not went out during request. But I can propose these variants:
1. Lets reuse `bucket_pin()` for this. Continue persist the fact of pinning, but on a second and other pins just increment an in-memory Lua counter. It looks ok since it is useful for the above described problem only, and on the instance restart anyway all requests are terminated, so after recovery it will not matter how many pins the bucket had had.
2. Introduce `bucket_ref()` - it is like full in-memory pin. Reference counter is not persisted and just protects the bucket from transfer until restart or requests end. Im my opinion, most useful way.
3. Just forgot about this problem. Storage already has function `bucket_check_state()`, so we can expose it to the public API and a user can call it after a yield.

First two proposals can be encapsulated inside a new router function like `vshard.router.atomic/atomicro/atomicrw` that calls on the storage `ref/pin` before a user function call, and calls `unref/unpin` after. But it can block rebalancing under heavy RPS that is very undesirable.

Lets consult customers: @racktear, @mons.

**Comment by Khatskevich** [comment]
In-memory reference counter is considered the best option here.

Next question: API. Suggestions:
1. Do explicit ref/unref: automatically for the whole `call` duration.
   a) Adv: user-code works safe by default
   b) Adv: if someone needs to avoid the `lock`, `call` option `non_lock` can be added in future
2. Do implicit `lock` by calling functions like `vshard.storage.lock_bucket(id)`
   a) Dis: The `lock`/`unlock` functions should be used in almost any user_funciton which do yield
      1. User can forget about it
      2. Extra, redundant code

   b) Dis: [to user_function] bucket_id should be passed somehow to call `lock` on the bucket.
   c) Dis: [in user_function] If one did yield and calls `lock` after it, an error may be triggered (bucket could have started reallocation)
   d) Adv: the API is more flexible

**Comment by Mons** [comment]
Implicit ref looks good. With workaround for non_ref.
Under high RPS there is a possibility to never move bucket. Because of always present "lock" while something yields.
So, there is a need for "migrating" state, when locked transactions finish to work, but incoming delayed for some time.
If all locks release within that time, then migration will start and requests will be rerouted
If locks don't release within that time, then migration will be delayed and requests preceed

**Comment by Khatskevich** [comment]
blocked by #126
