### ISSUE TITLE
Allow multiple routers in an instance

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#130]

**Comment by Khatskevich** [comment]
Main use case: there is a number of clusters and application uses all of them.
Pros:
1. admin have to maintain a lot of instances of Tarantool and its `ip:port`
2. instead of just calling a router method, one has to call router method over a network (extra hope)

Cons:
1. the feature require different API: `vshard_instance:method()` (current API: `vshard.router.method()`)
  a. change API?
  b. support 2 APIs?
2. have to maintain multiple copies of Vshard and its fibers and reload of all of them (in case of reloading)
3. have to give names to routers to make logs readable

**Comment by Gerold103** [comment]
We will not change API. It is not a thing to discuss.

**Comment by opomuc** [comment]
@Khatskevich how about `vshard.<cluster_name>.router.method()`?
