### ISSUE TITLE
Speed up moving empty buckets

### ISSUE THREAD

**Issue by rosik** [tarantool/vshard#151]
I don't like to call vshard.router.bootstrap manually, so I do it automatically after every new storage added.
The first bootstrap creates 3000 buckets on storage-1, and the second bootstrap does nothing, but makes rebalancing possible, but it's too slow.

My proposal is to instantly rebalance empty buckets on vhard.router.bootstrap.
Or at least speed up rebalancing of empty buckets. It may be discussed.

**Comment by Gerold103** [comment]
If you want to speed up rebalancing, you can play (increase) with `rebalancer_max_receiving` setting. VShard will not rebalance empty buckets all at the same time since buckets transfer is a heavy operation regardless of bucket emptiness. So vshard makes a time gap between transfer of some number of buckets.

Also maybe it would be useful to expose `vshard.consts.REBALANCER_WORK_INTERVAL` to configuration so as to allow you to decrease interval between rebalancing rounds.

**Comment by rosik** [comment]
Ok. I will refactor the logic and make bootstrap operation manual.
