### ISSUE TITLE
flaky test: rebalancer/stress_add_remove_rs.test.lua (on memtx) hangs

### ISSUE THREAD

**Issue by kyukhin** [tarantool/vshard#309]
The log can be seen [here](https://github.com/tarantool/tarantool/runs/4664663482?check_suite_focus=true#step:7:68).

**Comment by Totktonada** [comment]
The logs in CI expire after some time (don't remember precisely, several months), so I suggest to attach them into issues.

[logs.txt](https://github.com/tarantool/vshard/files/7794831/logs.txt)

**Comment by Gerold103** [comment]
Hangs on vinyl too sometimes. The reason is that `rebalancer_utils.start_loading()`, if called more than once during one test run, creates duplicate primary keys. Because it uses `write_iterations` as pk, which is reset to 0 on each `start_loading()`. A good-enough fix could be to truncate the test space before doing next `start_loading()`.

Also as a safety measure it is worth limiting `write_iterations` somehow. For example, make it max `N * bucket_count` and increment by modulo of this value. Then it is limited and it won't produce duplicate pks.

**Comment by Serpentian** [comment]
However, I could do something wrong about truncating spaces. Here's the draft PR with truncating: #349. Unfortunately, this test passed on CI this time, but if you restart it several times it will fail some day.

**Comment by Gerold103** [comment]
> Moreover, why do we bother about duplicated primary keys when in do_write_load we call do_replace.

If you start load, then stop it, and start again, then you will start with write_iterations 0 again. That causes `replace`s of the already generated primary keys into potentially other buckets. So you get tuples like `{1, 10}` and `{1, 20}` in buckets 10 and 20 on different replicasets. But when rebalancer tries to put buckets 10 and 20 onto a same replicaset, they fail with the duplicate primary key `{1}` error. I can definitely say this was one of the reasons why the test fails, because I saw in the logs an error about duplicate primary key when it clashed from 2 different buckets. Doesn't mean though that this is the only reason.

> The problem is definitely in this cancelled fiber on storage.

It doesn't necessarily mean it was cancelled on the storage. More likely it was cancelled on the router. The netbox internal fiber, for instance. Something could go wrong inside of it.

**Comment by Serpentian** [comment]
Most likely, the issue is related to #341

**Comment by Gerold103** [comment]
I wouldn't be so sure. In #341 they kill all the fibers explicitly. In the tests we don't do that.

**Comment by Gerold103** [comment]
Sorry, truncation was never needed. I figured out the reason, See the attached PR above.
